settings:
  legacy:
    force: false
    interval: 100ms
server:
  status: false
  open: false
  port: 5001
  host: localhost
schema:
- name: operacao-viajante-api
  path: .
  environment:
    debug: "true"
  commands:
    fix:
      status: true
    run:
      status: true
  watcher:
    paths:
    - /
    extensions:
    - go
    - json
    - yml
    ignored_paths:
    - .git
    - .github
    - .realize
    - Godeps
    - operacao-viajante-api
    - operacao-viajante-api-go-tmp-umask
    - vendor
    scripts:
    - type: after
      command: make test-dev
      output: true
